/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

/**
 *
 * @author chhav
 */
public class Brinjal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Brinjal
     */
    public Brinjal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/brinjal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 50, 260, 210);

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("* It is a vegetable.");
        getContentPane().add(label1);
        label1.setBounds(130, 270, 200, 30);

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("* It is ful of vitamins");
        getContentPane().add(label2);
        label2.setBounds(130, 310, 190, 30);

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setText(" Brinjal");
        getContentPane().add(label3);
        label3.setBounds(220, 10, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
