/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

/**
 *
 * @author chhav
 */
@SuppressWarnings("serial")
public class CropInformation extends javax.swing.JFrame {

    /**
     * Creates new form CropInformation
     */
    public CropInformation() {
        initComponents();
       // this.setExtenedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp1 = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label1 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu25 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu35 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu36 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu38 = new javax.swing.JMenu();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu39 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu40 = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu43 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu46 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu47 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu50 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu52 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu57 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu58 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu59 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenu60 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu61 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu62 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu63 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu64 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu65 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenu66 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        Maize = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        dp1.setBackground(new java.awt.Color(255, 204, 204));
        dp1.add(jDesktopPane1);
        jDesktopPane1.setBounds(410, 200, 0, 0);

        label2.setBackground(new java.awt.Color(204, 255, 204));
        label2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label2.setText("* Rabi Crops");
        dp1.add(label2);
        label2.setBounds(140, 120, 260, 48);

        label3.setBackground(new java.awt.Color(204, 255, 204));
        label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label3.setText("* Khrif Crops");
        dp1.add(label3);
        label3.setBounds(140, 190, 250, 40);

        label4.setBackground(new java.awt.Color(204, 255, 204));
        label4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label4.setText("* Zaid Crops");
        dp1.add(label4);
        label4.setBounds(140, 250, 240, 40);

        label5.setBackground(new java.awt.Color(204, 255, 204));
        label5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label5.setText("* Plantation Crops");
        dp1.add(label5);
        label5.setBounds(140, 310, 340, 50);

        label6.setBackground(new java.awt.Color(204, 255, 204));
        label6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label6.setText("* Cash Crops");
        dp1.add(label6);
        label6.setBounds(140, 380, 260, 40);

        label7.setBackground(new java.awt.Color(204, 255, 204));
        label7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label7.setText("* Vegetables ");
        dp1.add(label7);
        label7.setBounds(140, 440, 250, 50);

        label8.setBackground(new java.awt.Color(204, 255, 204));
        label8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label8.setText("*  Fruits");
        dp1.add(label8);
        label8.setBounds(140, 500, 170, 40);

        label1.setBackground(new java.awt.Color(204, 255, 204));
        label1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label1.setText(" Crop Informations");
        dp1.add(label1);
        label1.setBounds(140, 30, 360, 70);

        getContentPane().add(dp1);
        dp1.setBounds(20, 10, 540, 610);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/GreenCropImage.jpg"))); // NOI18N
        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 10, 470, 610);

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 0));
        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 10, true));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(0, 102, 0));
        jMenu1.setText("RabiCrops");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jMenu20.setText("Wheat");

        jMenuItem2.setText("Sown In Mid November");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem2);

        jMenu22.setText("Hervested In  April May");
        jMenu20.add(jMenu22);

        jMenuItem1.setText("A land Area Crop");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem1);

        jMenuItem9.setText("WheatInformation");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem9);

        jMenu1.add(jMenu20);

        jMenu23.setText("MusteredOil");
        jMenu23.add(jMenuItem4);

        jMenuItem12.setText("MusteredOil");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem12);

        jMenu1.add(jMenu23);

        jMenu25.setText("Oats");

        jMenuItem36.setText("Oats");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu25.add(jMenuItem36);

        jMenu1.add(jMenu25);

        jMenu27.setText("Linseed");

        jMenuItem37.setText("Linseed");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu27.add(jMenuItem37);

        jMenu1.add(jMenu27);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(0, 102, 0));
        jMenu4.setText("KharifCrops");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenu33.setText("Arhar");

        jMenuItem13.setText("Arhar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu33.add(jMenuItem13);

        jMenu4.add(jMenu33);

        jMenu35.setText("GroundNut");

        jMenuItem38.setText("Groundnut");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu35.add(jMenuItem38);

        jMenu4.add(jMenu35);

        jMenu36.setText("Cotton");

        jMenuItem14.setText("Cotton");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu36.add(jMenuItem14);

        jMenu4.add(jMenu36);

        jMenuBar1.add(jMenu4);
        jMenuBar1.add(jMenu5);
        jMenuBar1.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(0, 102, 0));
        jMenu7.setText("ZaidCrops");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jMenu37.setText("Pumpkin");

        jMenuItem15.setText("Pumkin");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu37.add(jMenuItem15);

        jMenu7.add(jMenu37);

        jMenu38.setText("BitterGround");

        jMenuItem39.setText("BitterGuard");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu38.add(jMenuItem39);

        jMenu7.add(jMenu38);

        jMenu39.setText("Watermelon");

        jMenuItem40.setText("Watermelon");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu39.add(jMenuItem40);

        jMenu7.add(jMenu39);

        jMenu40.setText("MuskMelon");

        jMenuItem41.setText("MuskMelon");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu40.add(jMenuItem41);

        jMenu7.add(jMenu40);

        jMenuBar1.add(jMenu7);
        jMenuBar1.add(jMenu8);

        jMenu9.setForeground(new java.awt.Color(0, 102, 0));
        jMenu9.setText("PlantationCrops");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jMenu41.setText("Coffee");

        jMenuItem16.setText("Coffee");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu41.add(jMenuItem16);

        jMenu9.add(jMenu41);

        jMenu43.setText("Tea");

        jMenuItem17.setText("Tea");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu43.add(jMenuItem17);

        jMenu9.add(jMenu43);

        jMenu46.setText("Oilseads");

        jMenuItem19.setText("Oilseeds");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu46.add(jMenuItem19);

        jMenu9.add(jMenu46);

        jMenu47.setText("RubberTrees");

        jMenuItem20.setText("RubberTrees");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu47.add(jMenuItem20);

        jMenu9.add(jMenu47);

        jMenuBar1.add(jMenu9);
        jMenuBar1.add(jMenu10);
        jMenuBar1.add(jMenu11);

        jMenu12.setForeground(new java.awt.Color(0, 102, 0));
        jMenu12.setText("CashCrops");
        jMenu12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jMenu48.setText("Coffee");

        jMenuItem21.setText("Coffee");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu48.add(jMenuItem21);

        jMenu12.add(jMenu48);

        jMenu50.setText("Tea");

        jMenuItem22.setText("Tea");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu50.add(jMenuItem22);

        jMenu12.add(jMenu50);

        jMenu52.setText("Cotton");

        jMenuItem23.setText("Cotton");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu52.add(jMenuItem23);

        jMenu12.add(jMenu52);

        jMenuBar1.add(jMenu12);
        jMenuBar1.add(jMenu13);
        jMenuBar1.add(jMenu14);

        jMenu15.setForeground(new java.awt.Color(0, 102, 51));
        jMenu15.setText("Vegetables");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu57.setText("CauliFlower");

        jMenuItem26.setText("CauliFlower");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu57.add(jMenuItem26);

        jMenu15.add(jMenu57);

        jMenu58.setText("Cucumber");

        jMenuItem27.setText("Cucumber");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu58.add(jMenuItem27);

        jMenu15.add(jMenu58);

        jMenu59.setText("Tometo");

        jMenuItem28.setText("Tometo");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu59.add(jMenuItem28);

        jMenu15.add(jMenu59);

        jMenu60.setText("Poteto");

        jMenuItem29.setText("Poteto");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu60.add(jMenuItem29);

        jMenu15.add(jMenu60);

        jMenu61.setText("Brinjal");

        jMenuItem30.setText("Brinjal");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu61.add(jMenuItem30);

        jMenu15.add(jMenu61);

        jMenuBar1.add(jMenu15);
        jMenuBar1.add(jMenu16);
        jMenuBar1.add(jMenu17);
        jMenuBar1.add(jMenu18);

        jMenu19.setForeground(new java.awt.Color(0, 102, 0));
        jMenu19.setText("Fruits");
        jMenu19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jMenu62.setText("Apple");

        jMenuItem31.setText("Apple");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu62.add(jMenuItem31);

        jMenu19.add(jMenu62);

        jMenu63.setText("Banana");

        jMenuItem32.setText("Banana");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu63.add(jMenuItem32);

        jMenu19.add(jMenu63);

        jMenu64.setText("Mango");

        jMenuItem33.setText("Mango");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu64.add(jMenuItem33);

        jMenu19.add(jMenu64);

        jMenu65.setText("Guava");

        jMenuItem34.setText("Guava");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu65.add(jMenuItem34);

        jMenu19.add(jMenu65);

        jMenu66.setText("Papaya");

        jMenuItem35.setText("Papaya");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu66.add(jMenuItem35);

        jMenu19.add(jMenu66);

        jMenu29.setText("Maize");

        Maize.setText("MaizeInformaion");
        Maize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaizeActionPerformed(evt);
            }
        });
        jMenu29.add(Maize);

        jMenu19.add(jMenu29);

        jMenuBar1.add(jMenu19);
        jMenuBar1.add(jMenu24);
        jMenuBar1.add(jMenu26);

        jMenu28.setForeground(new java.awt.Color(0, 102, 51));
        jMenu28.setText("Next");
        jMenu28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu28ActionPerformed(evt);
            }
        });

        jMenuItem42.setText("Next");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu28.add(jMenuItem42);

        jMenuBar1.add(jMenu28);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:   
        //KhrifCrops ch1 = new  KhrifCrops();
        //this.dp1.add(ch1);
        //ch1.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void MaizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaizeActionPerformed
      
        Maize ch2= new Maize();
        this.dp1.add(ch2);
        ch2.setVisible(true);


// TODO add your handling code here:
    }//GEN-LAST:event_MaizeActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         wheatinfo ch12;
        ch12 = new wheatinfo();
        this.dp1.add(ch12);
        ch12.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
         MusteredOil ch5= new MusteredOil();
        this.dp1.add(ch5);
        ch5.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
       Cotton ch12= new Cotton();
        this.dp1.add(ch12);
        ch12.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Coffee ch16= new Coffee();
        this.dp1.add(ch16);
        ch16.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        Poteto ch33= new Poteto();
        this.dp1.add(ch33);
        ch33.setVisible(true);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
         Oats ch6= new Oats();
        this.dp1.add(ch6);
        ch6.setVisible(true);



// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        LinSeed ch9= new LinSeed();
        this.dp1.add(ch9);
        ch9.setVisible(true);
        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Arhar ch10= new Arhar();
        this.dp1.add(ch10);
        ch10.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        Groundnut ch11= new Groundnut();
        this.dp1.add(ch11);
        ch11.setVisible(true);
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        Pumpkin ch13= new Pumpkin();
        this.dp1.add(ch13);
        ch13.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
       BitterGuard ch14= new BitterGuard ();
        this.dp1.add(ch14);
        ch14.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        Watermelon ch15= new Watermelon();
        this.dp1.add(ch15);
        ch15.setVisible(true);
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        Muskmelon ch15= new Muskmelon();
        this.dp1.add(ch15);
        ch15.setVisible(true);
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        Tea ch17= new Tea();
        this.dp1.add(ch17);
        ch17.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        Oilseeds ch18= new Oilseeds();
        this.dp1.add(ch18);
        ch18.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
       RubberTrees ch20= new RubberTrees();
        this.dp1.add(ch20);
        ch20.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        Coffee ch20= new Coffee();
        this.dp1.add(ch20);
        ch20.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        Tea ch21= new Tea();
        this.dp1.add(ch21);
        ch21.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        Cotton ch22= new Cotton();
        this.dp1.add(ch22);
        ch22.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
       
        CauliFlower ch40= new CauliFlower();
        this.dp1.add(ch40);
        ch40.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
      Cucumber ch42= new Cucumber();
        this.dp1.add(ch42);
        ch42.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        Tometo ch32= new Tometo();
        this.dp1.add(ch32);
        ch32.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
       Brinjal  ch33= new Brinjal();
        this.dp1.add(ch33);
        ch33.setVisible(true);
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        Apple ch51= new Apple();
        this.dp1.add(ch51);
        ch51.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        Banana ch56= new Banana();
        this.dp1.add(ch56);
        ch56.setVisible(true);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
      Mango ch60= new Mango();
        this.dp1.add(ch60);
        ch60.setVisible(true); 
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        Guava ch62= new Guava();
        this.dp1.add(ch62);
        ch62.setVisible(true);
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        Papaya ch63= new Papaya();
        this.dp1.add(ch63);
        ch63.setVisible(true);
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenu28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu28ActionPerformed
       
       new HomePage().setVisible(true);



// TODO add your handling code here:
    }//GEN-LAST:event_jMenu28ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
       new HomePage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CropInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CropInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CropInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CropInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CropInformation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Maize;
    private javax.swing.JDesktopPane dp1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu57;
    private javax.swing.JMenu jMenu58;
    private javax.swing.JMenu jMenu59;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu60;
    private javax.swing.JMenu jMenu61;
    private javax.swing.JMenu jMenu62;
    private javax.swing.JMenu jMenu63;
    private javax.swing.JMenu jMenu64;
    private javax.swing.JMenu jMenu65;
    private javax.swing.JMenu jMenu66;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    // End of variables declaration//GEN-END:variables

   // void setVisible() {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}

    

    
}
