/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

/**
 *
 * @author chhav
 */
public class Cucumber extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cucumber
     */
    public Cucumber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyPackage/Cucumberimg.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 40, 260, 170);

        label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label1.setText("* This is Full  of Vitamins and Protins");
        getContentPane().add(label1);
        label1.setBounds(110, 260, 340, 40);

        label2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label2.setText("* This is sown in SandySoil ");
        getContentPane().add(label2);
        label2.setBounds(110, 300, 260, 30);

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("* This is full of Water");
        getContentPane().add(label3);
        label3.setBounds(110, 370, 190, 30);

        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setText("* This is Sown In Summer Seasson");
        getContentPane().add(label4);
        label4.setBounds(110, 330, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
