/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author chhav
 */
@SuppressWarnings("serial")
public class Sell extends javax.swing.JFrame {

    /**
     * Creates new form Sell
     */
    public Sell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        AcceptBtn = new javax.swing.JButton();
        tf20 = new javax.swing.JTextField();
        label10 = new java.awt.Label();
        tf9 = new javax.swing.JTextField();
        label11 = new java.awt.Label();
        tf8 = new javax.swing.JTextField();
        totalBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setBackground(new java.awt.Color(153, 153, 255));
        label1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label1.setText(" Sell");
        getContentPane().add(label1);
        label1.setBounds(322, 25, 90, 48);

        label2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label2.setText(" CropId");
        getContentPane().add(label2);
        label2.setBounds(82, 93, 85, 35);

        label3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label3.setText("CropName");
        getContentPane().add(label3);
        label3.setBounds(258, 93, 99, 35);

        label4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label4.setText("Quantity");
        getContentPane().add(label4);
        label4.setBounds(396, 93, 82, 35);

        label5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label5.setText("Departure Place");
        getContentPane().add(label5);
        label5.setBounds(531, 93, 151, 26);
        getContentPane().add(tf1);
        tf1.setBounds(82, 157, 85, 28);
        getContentPane().add(tf2);
        tf2.setBounds(258, 157, 99, 28);
        getContentPane().add(tf3);
        tf3.setBounds(396, 157, 82, 28);
        getContentPane().add(tf4);
        tf4.setBounds(531, 157, 151, 28);

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn);
        SubmitBtn.setBounds(557, 212, 95, 31);

        label6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label6.setText(" price/item");
        getContentPane().add(label6);
        label6.setBounds(60, 275, 104, 26);

        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText(" Departure Date");
        getContentPane().add(label7);
        label7.setBounds(60, 484, 141, 28);

        label8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label8.setText(" Departure Place");
        getContentPane().add(label8);
        label8.setBounds(60, 399, 149, 28);
        getContentPane().add(tf5);
        tf5.setBounds(60, 312, 131, 26);
        getContentPane().add(tf6);
        tf6.setBounds(291, 399, 160, 28);
        getContentPane().add(tf7);
        tf7.setBounds(291, 484, 160, 28);

        AcceptBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AcceptBtn);
        AcceptBtn.setBounds(557, 480, 105, 31);
        getContentPane().add(tf20);
        tf20.setBounds(557, 312, 105, 32);

        label10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label10.setText(" Arrival Date");
        getContentPane().add(label10);
        label10.setBounds(60, 524, 141, 26);
        getContentPane().add(tf9);
        tf9.setBounds(291, 519, 160, 31);

        label11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label11.setText(" Arrival Place");
        getContentPane().add(label11);
        label11.setBounds(60, 437, 129, 34);
        getContentPane().add(tf8);
        tf8.setBounds(291, 437, 160, 34);

        totalBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalBtn.setText("Total");
        totalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(totalBtn);
        totalBtn.setBounds(557, 270, 91, 31);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 700, 560);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 700, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
       
         final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
     final String DB_URL = "jdbc:mysql://localhost/cmarket";

    //Database credentials
    final String user = "root";
    final String pass = "";
    // final string address = " "
    // public static void main(String[] args) {
     Connection conn = null;
     Statement stmt = null;
     try{
     //STEP 2: Register JDBC driver
      Class.forName("com.mysql.jdbc.Driver");

      //STEP 3: Open a connection
      System.out.println("Connecting to a selected database...");
      conn = java.sql.DriverManager.getConnection(DB_URL, user, pass);
      System.out.println("Connected database successfully...");
      
      //STEP 4: Execute a query
      System.out.println("Inserting records into the table...");
      stmt = conn.createStatement();
      String cropid = tf1.getText();
      String cropname;
         cropname = tf2.getText();
      String quantity;
         quantity = tf3.getText();
      String departureplace = tf4.getText();
    
     // ResultSet sql;
     //this is for inserting the single vale inthe table
     // String sql = "INSERT INTO  cropinformation values('"+cropname+"')";
     //this is for the inserting multipal value in the table;
       String sql = "INSERT INTO sell(cropid, cropname, Quantity, departureplace)"+"values('"+cropid+"','"+cropname+"','"+quantity+"','"+departureplace+"')";
       stmt.executeUpdate(sql);
      //String tpl = "insert into cropinformation values('"+soiltype+"')";
      //String sql = "SELECT  ("soiltype FROM cropsinformation where cropname = wheat")";
     // stmt.executeUpdate(sql);
      //stmt.executeUpdate(tpl);
      
     // while(sql.next(sql));
     
   }catch(SQLException | ClassNotFoundException se){
         //Handle errors for JDBC

   }
        //Handle errors for Class.forName
        finally{
      //finally block used to close resources
      try{
         if(stmt!=null)
            conn.close();
      }catch(SQLException se){
      }// do nothing
      try{
         if(conn!=null)
            conn.close();
      }catch(SQLException se){
      }//end finally try
   }//end try
    

JOptionPane.showMessageDialog(null, "Your data submitted Successfully");
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
       
        
        
        
        
        
         try{
                 Class.forName("com.mysql.jdbc.Driver");
                 try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cmarket","root",""))
                 {
                     String sql;
                     sql = "select * from csell  where cropid =?";
                     
                     PreparedStatement ps;
                     ps = con.prepareStatement(sql);
                     ps.setString(1,tf1.getText());
                     ResultSet rst;
                     rst = ps.executeQuery();
                     if(rst.next())
                     {
                         tf5.setText(rst.getString("price"));
                        
                         tf6.setText(rst.getString("departureplace"));
                          tf8.setText(rst.getString("arrivalplace"));
                         tf7.setText(rst.getString("departuredate"));
                         tf9.setText(rst.getString("arrivaldate"));
                     }   
                 }
           
             } catch (ClassNotFoundException | SQLException e) {
               JOptionPane.showMessageDialog(null, "Your selling Succefully");
             }
         JOptionPane.showMessageDialog(null, "Your selling Succefully");
         new HomePage().setVisible(true);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void totalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtnActionPerformed

        
                 try{
                        //tf3.setText("");
                            //tf5.setText("");
                           // tf20.setText("");

                 Class.forName("com.mysql.jdbc.Driver");
                 try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cmarket","root",""))
                 {
                   
                     String sql;
                     sql = "select price from csell  where cropid =?";
                     sql = "select quantity from sell  where cropid =?";
                   
                    // ps.setString(1,tf1.getText());
                     ResultSet rst;
                     rst = null;
                    try
                    {
                             tf20.setText("");
                           // if(totalBtn.isSelected()==true)
                            {
                               int num1 = Integer.parseInt(tf5.getText());
                               int num2 = Integer.parseInt(tf3.getText());

                              
                              int  total = (num1)*(num2);
                             // total = Integer.valueOf(total);
                              // String total = String.valueOf(total);
                              tf20.setText(Integer.toString(total));
                              JOptionPane.showMessageDialog(null,"The total is: "+total,"total:",JOptionPane.INFORMATION_MESSAGE);
                            }
                            
                        }catch(NumberFormatException e)
                        {
                             JOptionPane.showMessageDialog(null, "Please Input a Integer","Error",JOptionPane.ERROR_MESSAGE);
                        }
// TODO add your handling code here:
// TODO add your handling code here:
                 }
         }catch (ClassNotFoundException | SQLException e) {
               JOptionPane.showMessageDialog(null, "Your selling Succefully");
             }
         
// TODO add your handling code here:
       
    }//GEN-LAST:event_totalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf20;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    private javax.swing.JButton totalBtn;
    // End of variables declaration//GEN-END:variables
}
